import ReactMarkdown from "react-markdown";
import {
  Bot,
  User,
  Copy,
  Check,
  ThumbsUp,
  ThumbsDown,
} from "lucide-react";
import { useState } from "react";

function Message({ sender, text }) {
  const [copied, setCopied] = useState(false);

  const isUser = sender === "user";

  const copyText = async () => {
    await navigator.clipboard.writeText(text);

    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 1500);
  };

  return (
    <div
      className={`flex items-start gap-4 ${
        isUser ? "justify-end" : "justify-start"
      }`}
    >
      {/* AI Avatar */}

      {!isUser && (
        <div className="flex-shrink-0">

          <div className="w-11 h-11 rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 flex items-center justify-center shadow-lg">

            <Bot size={20} />

          </div>

        </div>
      )}

      {/* Message */}

      <div
        className={`

          ${
            isUser
              ? "max-w-[75%] bg-gradient-to-r from-blue-600 to-indigo-600 text-white"
              : "w-full max-w-[900px] bg-slate-800 border border-slate-700"
          }

          rounded-3xl
          px-7
          py-6
          shadow-lg
          transition-all
        `}
      >
        <ReactMarkdown
          components={{
            h1: ({ children }) => (
              <h1 className="text-3xl font-bold mb-5">
                {children}
              </h1>
            ),

            h2: ({ children }) => (
              <h2 className="text-2xl font-bold mb-4">
                {children}
              </h2>
            ),

            h3: ({ children }) => (
              <h3 className="text-xl font-semibold mb-3">
                {children}
              </h3>
            ),

            p: ({ children }) => (
              <p className="leading-8 text-[16px] mb-4 text-slate-200">
                {children}
              </p>
            ),

            ul: ({ children }) => (
              <ul className="list-disc ml-6 space-y-2 mb-5">
                {children}
              </ul>
            ),

            ol: ({ children }) => (
              <ol className="list-decimal ml-6 space-y-2 mb-5">
                {children}
              </ol>
            ),

            li: ({ children }) => (
              <li className="leading-7">
                {children}
              </li>
            ),

            strong: ({ children }) => (
              <strong className="font-semibold text-white">
                {children}
              </strong>
            ),

            code: ({ children }) => (
              <code className="bg-slate-900 text-green-400 rounded-lg px-2 py-1">
                {children}
              </code>
            ),

            blockquote: ({ children }) => (
              <blockquote className="border-l-4 border-blue-500 pl-4 italic text-slate-300 my-4">
                {children}
              </blockquote>
            ),
          }}
        >
          {text}
        </ReactMarkdown>

        {/* Footer */}

        {!isUser && (

          <div className="mt-6 pt-5 border-t border-slate-700 flex items-center justify-between">

            <div>

              <p className="text-xs text-slate-500">

                Generated by ResumeGPT • Groq LLM

              </p>

            </div>

            <div className="flex items-center gap-3">

              <button
                onClick={copyText}
                className="w-9 h-9 rounded-xl hover:bg-slate-700 transition flex items-center justify-center"
              >
                {copied ? (
                  <Check size={18} className="text-green-400" />
                ) : (
                  <Copy size={18} />
                )}
              </button>

              <button className="w-9 h-9 rounded-xl hover:bg-slate-700 transition flex items-center justify-center">

                <ThumbsUp size={18} />

              </button>

              <button className="w-9 h-9 rounded-xl hover:bg-slate-700 transition flex items-center justify-center">

                <ThumbsDown size={18} />

              </button>

            </div>

          </div>

        )}

      </div>

      {/* User Avatar */}

      {isUser && (

        <div className="flex-shrink-0">

          <div className="w-11 h-11 rounded-full bg-slate-700 flex items-center justify-center shadow-lg">

            <User size={20} />

          </div>

        </div>

      )}

    </div>
  );
}

export default Message;